name: Generate Commit Summary

on:
  push:
    branches:
      - main # Or your main branch

jobs:
  generate_summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history (or adjust if needed - see explanation below)

      - name: Set Previous Commit Hash
        id: set_previous_hash
        uses: actions/github-script@v6  # Use GitHub script for input
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const previousHash = core.getInput('previous_hash'); // Get input from workflow dispatch
            if (!previousHash) {
              core.setFailed('Missing required input: previous_hash');
              return; // Stop the workflow
            }
            core.setOutput('previous_hash', previousHash);

      - name: Generate Summary
        id: generate_summary
        run: |
          PREVIOUS_HASH="${{ steps.set_previous_hash.outputs.previous_hash }}"
          CURRENT_HASH="${{ github.sha }}"

          echo "Generating summary from $PREVIOUS_HASH to $CURRENT_HASH"

          DIFF=$(git diff --name-only $PREVIOUS_HASH $CURRENT_HASH)

          if [[ -z "$DIFF" ]]; then
            echo "No file changes found between commits."
            echo "::set-output name=summary::No file changes."
            exit 0
          fi

          SUMMARY="Changes in these files:\n"
          for file in $DIFF; do
            SUMMARY+="- $file\n"
          done

          echo "::set-output name=summary::$SUMMARY"

      - name: Output Summary (for testing)
        run: |
          echo "Commit Summary:"
          echo "${{ steps.generate_summary.outputs.summary }}"

      - name: Create or Update Comment
        uses: actions/github-script@v6
        if: github.event_name == 'push' # Only on pushes
        env:
          SUMMARY: ${{ steps.generate_summary.outputs.summary }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // ... (Same comment creation/update logic as before) ...


# Add a workflow_dispatch trigger to allow manual runs with input
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      previous_hash:
        description: 'Commit hash to start from'
        required: true # Make it required for manual runs